# Generated by Django 4.0.2 on 2022-04-24 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(max_length=200)),
                ('picture', models.FileField(blank=True, default='profile.webp', upload_to='')),
                ('picture1', models.FileField(blank=True, default='1.webp', upload_to='')),
                ('picture2', models.FileField(blank=True, default='2.webp', upload_to='')),
                ('picture3', models.FileField(blank=True, default='3.webp', upload_to='')),
                ('picture4', models.FileField(blank=True, default='4.webp', upload_to='')),
                ('picture5', models.FileField(blank=True, default='5.webp', upload_to='')),
                ('picture6', models.FileField(blank=True, default='6.webp', upload_to='')),
                ('picture7', models.FileField(blank=True, default='7.webp', upload_to='')),
                ('picture8', models.FileField(blank=True, default='8.webp', upload_to='')),
                ('picture9', models.FileField(blank=True, default='9.webp', upload_to='')),
                ('content_type', models.CharField(max_length=50)),
                ('following', models.ManyToManyField(related_name='followers', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('creation_time', models.DateTimeField()),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
